version: 2
sources:
  - name: bronze
    database: trends_lake
    schema: main
    description: "Bronze layer - raw data from lakehouse"
    tables:
      - name: keywords
        description: "Raw keyword data"
      - name: census
        description: "Raw census data"
      - name: search_results
        description: "Raw search results data"
      - name: video_statistics
        description: "Raw video statistics data"
      - name: google_trends
        description: "Raw google trends data"

  - name: silver
    description: "Cleaned and transformed data"
    tables:
      - name: faction_distribution
      - name: households
      - name: language_building_blocks
      - name: language_roots
      - name: moons
      - name: people
      - name: planets
      - name: region_biome
      - name: regions
